Default:

Drill:	drill.cpp
	g++ -g drill.cpp -o drill.out
Drill2: drill2.cpp
	g++ -g drill2.cpp -o drill2.out

trythis:	trythis.cpp
	g++ trythis.cpp -o try.out

.PHONY: clean
clean: 
	rm -f *.out
    
