Default:

Problem2:	problem2.cpp
	g++ -g problem2.cpp -o problem2.out
Problem6:	problem6.cpp
	g++ -g problem6.cpp -o problem6.out
Problem7:	problem7.cpp
	g++ -g problem7.cpp -o problem7.out
Problem9:	problem9.cpp
	g++ -g problem9.cpp -o problem9.out
Link: 	link.cpp link.h
	g++ -g link.cpp -o link.out

.PHONY: clean
clean:
	rm *.out
