Default:

Problem2:	problem2.cpp
	g++ -g problem2.cpp -o problem2.out
Problem9:	problem9.cpp
	g++ -g problem9.cpp -o problem9.out
Link.h:		Link.h
	g++ link.h
Link:		link.cpp
	g++ -g link.cpp -o link.out

.PHONY: clean
clean:
	rm *.out
